# This file is part of the DiscoPoP software (http://www.discopop.tu-darmstadt.de)
#
# Copyright (c) 2020, Technische Universitaet Darmstadt, Germany
#
# This software may be modified and distributed under the terms of
# the 3-Clause BSD License.  See the LICENSE file in the package base
# directory for details.

name: "Basic code checks"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  execute_license_check:
    runs-on: self-hosted
    name: License check
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: "Github SHA"
        run: |
          echo "Hello from: ${{ github.sha }}"

      

      - name: "Check all files for DiscoPoP License tag"
        run: |
          ./scripts/dev/check-license.sh $(find . -type f)

  execute_type_check:
    runs-on: self-hosted
    name: Type check
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: "Run MyPy Type Checker"
        run: |
          python3 -m mypy --config-file=mypy.ini -p .

  setup_venv:
    runs-on: self-hosted
    name: "Setup venv"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: "Setup venv"

        run: |
          echo "PWD: ${PWD}"
          python3 -m venv venv
  
  execute_format_check:
    runs-on: self-hosted
    name: "Format check"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: "Check formatting using black"
        run: |
          python3 -m black -l 120 --check .
